language: python

jobs:
  include:
    - python: 3.6
      env: DJANGO=3.0
    - python: 3.7
      env: DJANGO=3.0
    - python: 3.8
      env: DJANGO=3.0

    - python: 3.6
      env: DJANGO=3.1
    - python: 3.7
      env: DJANGO=3.1
    - python: 3.8
      env: DJANGO=3.1

    - python: 3.6
      env: DJANGO=master
    - python: 3.7
      env: DJANGO=master
    - python: 3.8
      env: DJANGO=master

    - stage: black
      python: 3.8
      install: pip install black
      script: black -l 120 --check --diff --color itelegram setup.py

  allow_failures:
    - env: DJANGO=master

install: pip install tox-travis
script: tox
